version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.16.0

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run: 
          name: Run tests
          command: npm test

      - run: 
          name: Deploy dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              serverless deploy --stage dev
            fi

      - run: 
          name: Deploy production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              serverless deploy --stage production
            fi
